export const state = {
  isActiveThreeDX: false,
  isActiveThreeDY: false,
  isActiveThreeDXY: false,
  isActiveCollapse: false,
  isActiveArrow: false,
  isActiveArrowAlt: false,
  isActiveArrowTurn: false,
  isActiveBoring: false,
  isActiveElastic: false,
  isActiveEmphatic: false,
  isActiveMinus: false,
  isActiveSlider: false,
  isActiveSpin: false,
  isActiveSpring: false,
  isActiveStand: false,
  isActiveSqueeze: false,
  isActiveVortex: false,
}
